# Configurações de Aplicação
spring:
  application:
    name: healthsync
  security:
    enabled: false

  # Configurações do Datasource
  datasource:
    url: jdbc:postgresql://health-sync-sena.crkmgwymgqyz.us-east-1.rds.amazonaws.com:5432/postgres  # URL do banco de dados PostgreSQL
    username: postgres                                # Usuário do banco de dados
    password: ${DATABASE_PASSWORD}                              # Senha do banco de dados
    driver-class-name: org.postgresql.Driver

  # Configurações de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update                                # Pode ser 'validate', 'update', 'create', 'create-drop'
    show-sql: true                                    # Exibe as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialeto específico do PostgreSQL

# Configurações de Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG                   # Define o nível de log para a camada web

# Configurações de Segurança
security:
  jwt:
    secret: 123456                               # Chave secreta para assinatura JWT
    expiration: 86400000                              # Expiração do token em milissegundos (1 dia)
